apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: au5s36i5i-java-quarkus
  janus-idp.io/tekton: au5s36i5i-java-quarkus
  backstage.io/kubernetes-id: au5s36i5i-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: au5s36i5i-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
